# constants!

# define these yourself

FARM_SIZE = get_world_size()
GRASS_UPPER_BOUND = 10000
WOOD_UPPER_BOUND = 10000
CARROT_UPPER_BOUND = ((GRASS_UPPER_BOUND / 2) + (WOOD_UPPER_BOUND / 2))
PUMPKIN_UPPER_BOUND = (CARROTS_UPPER_BOUND / 3)
WATER_GAIN_RATE = 0.8
