# constants!

# define these as upper bounds

FARM_SIZE = get_world_size()
GRASS_UPPER_BOUND = 10000
WOOD_UPPER_BOUND = 10000
CARROT_UPPER_BOUND = ((GRASS_UPPER_BOUND / 2) + (WOOD_UPPER_BOUND / 2))
PUMPKIN_UPPER_BOUND = 10000
WATER_THRESHOLD = (FARM_SIZE * 0.3)
